### ISSUE TITLE
YT?

### ISSUE THREAD

**Issue by ghost** [knarka/fikaba#15]
Is youtube support avail at all? Tinyib (similar code) has great youtube support, and if someone could make that work in this board that would be awesome. I will pay anyone to do it.

**Comment by knarka** [comment]
What kind of support do you mean? Video embeds in the place where you'd otherwise post an image, or embed buttons next to links in the post's text?
If you're serious about paying for this, shoot me an email at knarka@airmail.cc

**Comment by ghost** [comment]
Will send you an email soon
