### ISSUE TITLE
when renaming the config.example.php the imgboard.php tells me HTTP ERROR 500

### ISSUE THREAD

**Issue by HarunaFujiwara** [knarka/fikaba#17]
## Describe the bug
Basically i tried to set this up and when i renamed the config.example.php to config.php the imgboard.php doesnt seem to work

## To Reproduce
1. Go to http://128.0.120.63
2. Click on imgboard.php

## Client (please complete the following information):
 - OS: windows
 - Browser chrome

## Server (please complete the following information):
- OS: ubuntu 16.04
- Server: apache2
- SQL server: mysql
- Fikaba version: newest from today

**Comment by mxrnx** [comment]
Could you log into your server and give me the output of `tail /var/log/apache2/error.log -n 30`?

**Comment by HarunaFujiwara** [comment]
[Fri Mar 29 10:50:26.775642 2019] [:error] [pid 32109] [client 188.21.100.131:50848] PHP Notice:
referer: http://128.0.120.63/AX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 33, 
[Fri Mar 29 10:50:26.775647 2019] [:error] [pid 32109] [client 188.21.100.131:50848] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 33, 
referer: http://128.0.120.63/                                                                   
                                                                                                
  Use of undefined constant MAX_KB - assumed 'MAX_KB' in /var/www/html/strings/en.php on line 36
, referer: http://128.0.120.63/                                                                 
[Fri Mar 29 10:50:26.775658 2019] [:error] [pid 32109] [client 188.21.100.131:50848] PHP Notice:
  Use of undefined constant MAX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 36, 
                                                                                                
[Fri Mar 29 10:50:26.775663 2019] [:error] [pid 32109] [client 188.21.100.131:50848] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 36, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741225 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
                                                                                                
, referer: http://128.0.120.63/_KB - assumed 'MAX_KB' in /var/www/html/strings/en.php on line 27
[Fri Mar 29 11:04:03.741258 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 27, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741265 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 27, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741277 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_KB - assumed 'MAX_KB' in /var/www/html/strings/en.php on line 30
, referer: http://128.0.120.63/                                                                 
[Fri Mar 29 11:04:03.741283 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 30, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741288 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 30, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741294 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_KB - assumed 'MAX_KB' in /var/www/html/strings/en.php on line 33
, referer: http://128.0.120.63/                                                                 
[Fri Mar 29 11:04:03.741299 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 33, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741305 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 33, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741318 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_KB - assumed 'MAX_KB' in /var/www/html/strings/en.php on line 36
, referer: http://128.0.120.63/                                                                 
[Fri Mar 29 11:04:03.741324 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_W - assumed 'MAX_W' in /var/www/html/strings/en.php on line 36, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:03.741329 2019] [:error] [pid 32113] [client 188.21.100.131:58961] PHP Notice:
  Use of undefined constant MAX_H - assumed 'MAX_H' in /var/www/html/strings/en.php on line 36, 
referer: http://128.0.120.63/                                                                   
[Fri Mar 29 11:04:24.031476 2019] [mpm_prefork:notice] [pid 32103] AH00169: caught SIGTERM, shut
ting down                                                                                       
[Fri Mar 29 11:04:39.222580 2019] [mpm_prefork:notice] [pid 32521] AH00163: Apache/2.4.18 (Ubunt
u) configured -- resuming normal operations                                                     
[Fri Mar 29 11:04:39.222634 2019] [core:notice] [pid 32521] AH00094: Command line: '/usr/sbin/ap
ache2'                                                                                          
[Fri Mar 29 11:04:43.082180 2019] [:error] [pid 32524] [client 188.21.100.131:58971] PHP Fatal e
rror:  Call to undefined function mysqli_connect() in /var/www/html/imgboard.php on line 39, ref
erer: http://128.0.120.63/                                                                      
[Fri Mar 29 11:15:53.095945 2019] [:error] [pid 32525] [client 82.169.17.61:33536] PHP Fatal err
or:  Call to undefined function mysqli_connect() in /var/www/html/imgboard.php on line 39, refer
er: http://128.0.120.63/                                                                        
[Fri Mar 29 11:26:17.024716 2019] [mpm_prefork:notice] [pid 32521] AH00169: caught SIGTERM, shut
ting down                                                                                       
[Fri Mar 29 11:26:18.156580 2019] [mpm_prefork:notice] [pid 618] AH00163: Apache/2.4.18 (Ubuntu)
 configured -- resuming normal operations                                                       
[Fri Mar 29 11:26:18.156643 2019] [core:notice] [pid 618] AH00094: Command line: '/usr/sbin/apac
he2'                                                                                            
[Fri Mar 29 11:26:26.132343 2019] [:error] [pid 622] [client 188.21.100.131:59222] PHP Fatal err
or:  Call to undefined function mysqli_connect() in /var/www/html/imgboard.php on line 39, refer
er: http://128.0.120.63/                                                                        
[Fri Mar 29 11:28:18.969289 2019] [mpm_prefork:notice] [pid 618] AH00169: caught SIGTERM, shutti
ng down                                                                                         
[Fri Mar 29 11:28:20.094302 2019] [mpm_prefork:notice] [pid 682] AH00163: Apache/2.4.18 (Ubuntu)
 configured -- resuming normal operations                                                       
[Fri Mar 29 11:28:20.094352 2019] [core:notice] [pid 682] AH00094: Command line: '/usr/sbin/apac
he2'                                                                                            
[Fri Mar 29 11:28:30.228484 2019] [:error] [pid 686] [client 188.21.100.131:59239] PHP Fatal err
or:  Call to undefined function mysqli_connect() in /var/www/html/imgboard.php on line 39, refer
er: http://128.0.120.63/

**Comment by mxrnx** [comment]
It looks like your PHP doesn't have the [mysqli library](https://www.php.net/manual/en/mysqli.requirements.php) installed, which fikaba requires. Try installing it, that should solve your issue.

**Comment by HarunaFujiwara** [comment]
im such a subhuman
thank you so much
