### ISSUE TITLE
Manager panel says "you do not have the necessary permissions"

### ISSUE THREAD

**Issue by HarunaFujiwara** [knarka/fikaba#18]
## Describe the bug
Small bug, when i log in to the manager panel (keep in mind i have admin rights) it states "you do not have the necessary permissions"

## Screenshots
![image](https://user-images.githubusercontent.com/45967327/55233725-a95b9900-5229-11e9-9fa9-c6d4dba8576c.png)

## Client (please complete the following information):
 - OS: windows 7
 - Browser chrome

## Server (please complete the following information):
- OS: ubuntu 16.04
- Server: apache2
- SQL server: mysql
- Fikaba version: newest

## Additional context
Everything else works like a charm, just this bug (sometimes when i go to home it doesnt show me the posts below but thats ok)

**Comment by mxrnx** [comment]
You logging in with the default account? That one isn't allowed to do anything, except create an account to replace it. Try doing that, and make sure to grant the new one all the permissions you'd like it to have.

**Comment by HarunaFujiwara** [comment]
also, when trying to reply to a post i get this: 
Incorrect datetime value: '0' for column 'root' at row 1
