### ISSUE TITLE
"Incorrect datetime value: '0' for column 'root' at row 1" when trying to reply

### ISSUE THREAD

**Issue by HarunaFujiwara** [knarka/fikaba#19]
## Describe the bug
i couldnt quite find if this was solved or not so im asking

## To Reproduce
1. Go to http://gnoekien.tk
2. Click on "reply"
3. write text etc etc.

## Client (please complete the following information):
 - OS: windows
 - Browser chrome,firefox,ie

## Server (please complete the following information):
- OS: ubuntu
- Server: apache2
- SQL server: mysql
- Fikaba version: 181008

## Additional context
there are even more problems, when you delete a post and go to the main page, its still there

**Comment by mxrnx** [comment]
Interesting. I've never seen this one before, and I cannot seem to reproduce it on a local instance.
Could you give me the output of `tail /var/log/apache2/error.log -n 30` right after trying to reply? The error log might be able to tell us more here.

**Comment by HarunaFujiwara** [comment]
`[Mon Apr 01 11:27:55.267589 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: capcode in /var/www/html/imgboard.php on line 1291, referer: http://gnoekie
n.tk/imgboard.php?res=7                                                                         
[Mon Apr 01 11:27:55.267674 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: oekaki in /var/www/html/imgboard.php on line 1291, referer: http://gnoekien
.tk/imgboard.php?res=7                                                                          
[Mon Apr 01 11:27:55.268329 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: ext in /var/www/html/imgboard.php on line 522, referer: http://gnoekien.tk/
imgboard.php?res=7                                                                              
[Mon Apr 01 11:27:55.333770 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: dest in /var/www/html/imgboard.php on line 693, referer: http://gnoekien.tk
/imgboard.php?res=7                                                                             
[Mon Apr 01 11:27:55.338385 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: ext in /var/www/html/imgboard.php on line 734, referer: http://gnoekien.tk/
imgboard.php?res=7                                                                              
[Mon Apr 01 11:27:55.338422 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: W in /var/www/html/imgboard.php on line 735, referer: http://gnoekien.tk/im
gboard.php?res=7                                                                                
[Mon Apr 01 11:27:55.338431 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: H in /var/www/html/imgboard.php on line 736, referer: http://gnoekien.tk/im
gboard.php?res=7                                                                                
[Mon Apr 01 11:27:55.338443 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: md5 in /var/www/html/imgboard.php on line 739, referer: http://gnoekien.tk/
imgboard.php?res=7                                                                              
[Mon Apr 01 11:27:55.338450 2019] [:error] [pid 9922] [client 188.21.100.131:58478] PHP Notice: 
 Undefined variable: fsize in /var/www/html/imgboard.php on line 741, referer: http://gnoekien.t
k/imgboard.php?res=7   `




very weird

**Comment by HarunaFujiwara** [comment]
and im sorry to have so many errors, i wish it was easier :smile:

**Comment by mxrnx** [comment]
Yeah, it's odd. It's definitely something about your versions of PHP and MySQL that's causing this, I just wish I knew what. I'll dig for a bit. Can you give me the output of `php --ri mysqli` and `mysql --version` in the meantime?

**Comment by mxrnx** [comment]
Alright, I think I know what's causing this. Your SQL server or version, as opposed to many other ones, does not accept 0 as a valid datetime. I've tried patching this on branch [issue19](https://github.com/knarka/fikaba/tree/issue19). Can you pull from there and try if that solves your issue? Should be as easy as `git fetch; git checkout issue19; git pull`.

**Comment by HarunaFujiwara** [comment]
##The mysqli command
                                                                                                       
mysqli                                                                                                 
                                                                                                       
Client API library version => mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e0274
                                                                                                       
9b83 $                                                                                                 
Active Persistent Links => 0                                                                           
Active Links => 0nt Links => 0                                                                         
                                                                                                       
                                                                                                       
Directive => Local Value => Master Value                                                               
mysqli.max_persistent => Unlimited => Unlimited                                                        
                                                                                                       
mysqli.allow_persistent => On => On                                                                    
mysqli.rollback_on_cached_plink => Off => Off                                                          
mysqli.default_user => no value => no value                                                            
                                                                                                       
mysqli.default_pw => no value => no value                                                              
mysqli.default_port => 3306 => 3306                                                                    
mysqli.reconnect => Off => Offlue => no value                                                          
                                                                                                       
mysqli.allow_local_infile => On => On   

##the mysql version command
4 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**Comment by HarunaFujiwara** [comment]
I can tell you: the whole thing was fixed with this php file you updated!
and im happy to tell you that soon you will be able to take http://gnoekien.tk on your list of websites running this script! (dont worry if the site is down, im always using the same domain ;) )
