### ISSUE TITLE
[feature idea] Multiple Mod accounts

### ISSUE THREAD

**Issue by HarunaFujiwara** [knarka/fikaba#20]
This isnt a bug but more a feature idea if it isnt already implemented,
Adding more moderator accounts, admin, helper accounts to the board so we can "employ" some people to help
Btw, you can proudly add my board to the list of site using your board ;)

**Comment by RGBACatlord** [comment]
Multiple managers can already be created.
In Manager Mode, click on [Account Management].
In there, you can create new accounts.
Hope this helps.
