### ISSUE TITLE
General dev questions.

### ISSUE THREAD

**Issue by Maikuolan** [knarka/fikaba#21]
Hi @knarka,

A conversation that happened earlier tonight elsewhere; TL;DR; Someone asked me whether I could offhandedly recommend any good chan scripts for them to use. I couldn't, but did some quick googling, and found yours. Looked at the source; Spotted some easy potential improvements/PRs; Have some general dev questions.

- Which minimum compatible PHP versions are you targeting? (So that PRs won't break backwards-compatibility).
- Anything off-limits at the moment? (e.g., parts of the codebase that you're currently working on right now, which PRs could interfere with, etc).
- ..Accepting new PRs at the moment generally?

**Comment by mxrnx** [comment]
Hey @Maikuolan. The project is currently not under very active development, but I'm keeping an eye on the repo. To answer your questions:
* The current minimum version is 7.0, and I've just updated the README to reflect that.
* Nothing off-limits really, I'm not actively working on anything.
* PRs are very welcome.

**Comment by Maikuolan** [comment]
Sounds good! Cheers for the answers. :-)
