### ISSUE TITLE
How can I change timezone?

### ISSUE THREAD

**Issue by ghost** [knarka/fikaba#23]
Your script is nice, but my users are astonished, why they when write new post at for example 9 o'clock (in Europian time) they have in thread time 2 o'clock. Because, you forgot to add the ability to change time from JST to CEST. Please, check this issue and add this ability!

**Comment by mxrnx** [comment]
> you forgot to add the ability

I did no such thing. Your server's timezone is off, which is something _you_ have configured incorrectly (or more likely, not at all).
