### ISSUE TITLE
SQL Causing internal server error

### ISSUE THREAD

**Issue by RGBACatlord** [knarka/fikaba#3]
Hi, kinda new to this. For some reason, any SQL I write causes an internal server error. I'm not sure if it's that I configured SQL or fikaba wrong.

**Comment by mxrnx** [comment]
Hey, thanks for opening an issue. I'm gonna need some more information to determine what's happening here. Can you describe the steps you've taken, and show what's on the last line's of Apache's (assuming you use Apache) error log (probably in `/var/log/apache2/error.log`).

**Comment by RGBACatlord** [comment]
[error.log](https://github.com/knarka/fikaba/files/1993961/error.log)

**Comment by mxrnx** [comment]
Looks like you're using a newer version of PHP than what Fikaba was created with, and some of the standard functions Fikaba uses are deprecated in your version. I've been working on resolving this recently. If you want to, you can try the unstable version that I'm currently working on [here](https://github.com/knarka/fikaba/tree/mysqli), but it'll probably contain bugs right now. I'll keep this issue open until I've resolved this.

**Comment by RGBACatlord** [comment]
Now, the MySQL library is missing. I've downgraded to php5.6

**Comment by RGBACatlord** [comment]
Got it working, but now
```
[Fri May 11 22:20:06.520766 2018] [php7:notice] [pid 1461] [client 192.168.1.1:61648] PHP Notice:  Undefined index: mode in /var/www/html/imgboard.php on line 22
[Fri May 11 22:20:06.520808 2018] [php7:notice] [pid 1461] [client 192.168.1.1:61648] PHP Notice:  Undefined index: mode in /var/www/html/imgboard.php on line 22
[Fri May 11 22:20:24.200492 2018] [php7:error] [pid 1683] [client 192.168.1.1:61669] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/imgboard.php:40\nStack trace:\n#0 {main}\n  thrown in /var/www/html/imgboard.php on line 40
[Fri May 11 22:20:27.655290 2018] [php7:error] [pid 1460] [client 192.168.1.1:61670] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/imgboard.php:40\nStack trace:\n#0 {main}\n  thrown in /var/www/html/imgboard.php on line 40
```

**Comment by mxrnx** [comment]
The deprecated functions I mentioned earlier include the mysql_* functions you're missing here, as they got replaced by the mysqli_* functions. Looks like you're still on a version that no longer has them. What does running `php --version` give you? These functions were removed in version 7.0.0, according to the documentation.

**Comment by RGBACatlord** [comment]
Ok, 5.6 is on, but mysql_ is still deprecated

**Comment by RGBACatlord** [comment]
Wait, working, replies are broken tho
```
Incorrect datetime value: '0' for column 'root' at row 1
```

**Comment by mxrnx** [comment]
This should now be resolved if you grab the latest version from master.
