### ISSUE TITLE
text doesn't get written into posts

### ISSUE THREAD

**Issue by lirmwing** [knarka/fikaba#7]
It looks like when I try to make a new thread with an image and text, only the image is posted.
Trying to reply also with only text causes a Flood Detection error. I think it's coming from imgboard.php (should also note that I'm using the mysqli branch as my phpMyAdmin doesn't support the master).

**Comment by mxrnx** [comment]
This is the same problem as #3. PHP has deprecated the mysql_* family of functions used in the master, and the mysqli branch is an in progress fix of that, but as of yet broken as well. Your options are currently either downgrading your PHP version or waiting, as I can't say when exactly I'll have the time to fix this.

**Comment by lirmwing** [comment]
Does this extend to the first issue I had as well?

**Comment by mxrnx** [comment]
Yeah, that's because the code interacting with the database on the mysqli branch is still incomplete.

**Comment by mxrnx** [comment]
This is now resolved, please give the current master a try
